<?php 
// application/layouts/scripts/layout.phtml

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>


  <?php echo $this->headLink()->appendStylesheet('/layouts/global.css') ?>
  
  <?= $this->headScript() ?>
  <?= $this->jQuery(); ?>
 
</head> 
<body>

<div id="wrapper">

	<div id="header">
		<div id="menu">
		<?php 
		$menu = $this->navigation()->findOneByLabel('MENUTOP');
		echo $this->navigation()->menu()->setMaxDepth(0)->renderMenu($menu); ?>
		</div>
		<!-- end #menu -->
		<div id="search">
		<?=$this->drawBlock('Search');
		?>
		</div>
		<!-- end #search -->
	</div>
	<!-- end #header -->
	
	<div id="logo">
		<h1><a href="#">IGzCMS </a></h1>
		<p><em> Framwork based on Zend Framework</em></p>
	</div>
	<hr />

<div id="page">
<div id="content">
<?php
if($this->notificationMessages)
{
	echo '<div class="notificationMessage">' . $this->notificationMessages[0] . '</div>';
}
?>
<?php echo $this->layout()->content ?>

</div>
<!-- end #content -->
<div id="sidebar">
<ul>
<li>
<h2>MENU</h2>
<?php
$menu = $this->navigation()->findOneByLabel('MENUSIDE');
echo $this->navigation()->menu()->setMaxDepth(4)->renderMenu($menu); ?>
</li>
<?php
echo  $this->drawBlock('Left', array('<li>','</li>'));
?>
</ul>
</div>
<!-- end #sidebar -->
<div style="clear: both;">&nbsp;</div>
</div>
<!-- end #page -->
<!--Copyright (c) 2008 Sitename.com. All rights reserved. .-->
<div id="footer">
<p><?= stripslashes(sprintf($this->translate('copyright'), date("Y"), $this->siteName.' '));?></p>
</div>
<!-- end #footer -->
</div>

</body>
</html>
 
